# @package _global_

defaults:
  - _self_

# Run parameters
run:
  seed: 0
  eval_rollouts: 1000
  eval_max_steps: 288

# Environment overrides
env:
  name: ccasr-gfp-control

# Agent overrides
agent:
  name: pid
  kp: 8.889
  ki: 0.0067
  obs_field: F_normalized
  setpoint: 0.3125 # 25 (target) / 80 (normalizer)
  control_low: 0
  control_high: 1

# W&B settings
wandb:
  enabled: false
  project: myriad
  entity: lugagne-lab
  group: examples
  tags: ["bangbang", "ccasr-gfp", "constant"]
