# @package _global_

# --- Defaults ---
# This section tells Hydra where to find the default
# configurations for composable components.
defaults:
  - agent: random_agent
  - env: ccas_ccar_env
  - _self_

run:
  # --- Run Settings ---
  seed: 42
  total_timesteps: 1e7
  num_envs: 124

  # --- Training Settings ---
  batch_size: 256
  buffer_size: 10000
  scan_chunk_size: 128

  # --- Evaluation ---
  eval_frequency: 1e3
  eval_rollouts: 100
  eval_max_steps: 1000

  # --- Logging ---
  log_frequency: 1e3

wandb:
  enabled: true
  entity: lugagne-lab  # team or user name
  project: aion  # project name (will group runs)
  group: scrap  # sub-group within a project (eg, sweep or experiment name)
  job_type: train  # eg, train, eval, test
  run_name: null  # if null, a default name will be generated
  mode: offline  # 'online' or 'offline' (can later be synced)
  dir: null  # where to log results locally (default: ./wandb/.)
  tags: []  # list of tags that can be used for searching later
